interface List {
  AllowDeletion: string;
  AllowMultiResponses: string;
  AnonymousPermMask: string;
  Author: string;
  BaseType: string;
  Created: string;
  DefaultViewUrl: string;
  Description: string;
  Direction: string;
  DocTemplateUrl: string;
  EmailAlias: string;
  EnableAttachments: string;
  EnableFolderCreation: string;
  EnableMinorVersion: string;
  EnableModeration: string;
  EnablePeopleSelector: string;
  EnableResourceSelector: string;
  EnableVersioning: string;
  EnforceDataValidation: string;
  EventSinkAssembly: string;
  EventSinkClass: string;
  EventSinkData: string;
  ExcludeFromOfflineClient: string;
  FeatureId: string;
  Fields: {
    colName: string; // "tp_ContentTypeId"
    DisplaceOnUpgrade: boolean; // "TRUE"
    DisplayName: string; // "Content Type ID";
    FromBaseType: boolean; // "TRUE";
    Hidden: string; // "TRUE";
    ID: string; // "{03e45e84-1992-4d42-9116-26f756012634}";
    Name: string; // "ContentTypeId";
    ReadOnly: boolean; // "TRUE";
    RowOrdinal: string; // "0";
    Sealed: boolean; // "TRUE";
    SourceID: string; // "http://schemas.microsoft.com/sharepoint/v3";
    StaticName: string; // "ContentTypeId";
    Type: string; // "ContentTypeId";
    [key: string]: string | boolean;
  }[];
  Flags: string;
  HasExternalDataSource: string;
  HasRelatedLists: string;
  HasUniqueScopes: string;
  Hidden: string;
  ID: string;
  ImageUrl: string;
  IrmEnabled: string;
  IsApplicationList: string;
  ItemCount: string;
  LastDeleted: string;
  MajorVersionLimit: string;
  MajorWithMinorVersionsLimit: string;
  MaxItemsPerThrottledOperation: string;
  MobileDefaultViewUrl: string;
  Modified: string;
  MultipleDataList: string;
  Name: string;
  NoThrottleListOperations: string;
  Ordered: string;
  PreserveEmptyValues: string;
  ReadSecurity: string;
  RequireCheckout: string;
  RootFolder: string;
  ScopeId: string;
  SendToLocation: string;
  ServerTemplate: string;
  ShowUser: string;
  StrictTypeCoercion: string;
  ThrottleListOperations: string;
  ThumbnailSize: string;
  Title: string;
  Version: string;
  WebFullUrl: string;
  WebId: string;
  WebImageHeight: string;
  WebImageWidth: string;
  WorkFlowId: string;
  WriteSecurity: string;
  [key: string]: string | object;
}

export default List;
